config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :admins, :controllers => { :registrations => :registrations }
  devise_for :brokers, :controllers => { :registrations => :registrations }
  devise_for :buyers, :controllers => { :registrations => :registrations }

  root to: "welcome#index"

  resources :admins
  resources :brokers
  resources :buyers
  resources :stocks
  resources :broker_stocks
  resources :buyer_stocks, only: [:create, :index]

  # for manually creating new broker and buyer accounts
  get 'admins/new/broker' => 'admins#new_broker', as: 'new_broker_admin'
  get 'admins/new/buyer' => 'admins#new_buyer', as: 'new_buyer_admin'
  post 'admins/create_broker' => 'admins#create_broker', as: 'create_broker_admin'
  post 'admins/create_buyer' => 'admins#create_buyer', as: 'create_buyer_admin'

  # for editing broker and buyer accounts
  get 'admins/:id/edit/broker' => 'admins#edit_broker', as: 'edit_broker_admin'
  get 'admins/:id/edit/buyer' => 'admins#edit_buyer', as: 'edit_buyer_admin'
  put 'admins/:id/update_broker' => 'admins#update_broker', as: 'update_broker_admin'
  put 'admins/:id/update_buyer' => 'admins#update_buyer', as: 'update_buyer_admin'


  get 'admins/pending/broker' => 'admins#pending_broker_signup', as: 'pending_broker_signup_admin'
  put 'admins/:id/approve_broker' => 'admins#approve_broker_signup', as: 'approve_broker_admin'

  get 'brokers/:id/portfolio' => 'brokers#show_portfolio', as: 'broker_portfolio'
  get 'buyers/:id/portfolio' => 'buyers#show_portfolio', as: 'buyer_portfolio'

  get 'brokers/:id/transaction' => 'brokers#show_transaction', as: 'broker_transaction'
  get 'buyers/:id/transaction' => 'buyers#show_transaction', as: 'buyer_transaction'
  get 'admins/show/transaction' => 'admins#show_transaction', as: 'all_transactions'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admins/edit_broker.html.erb
<%= stylesheet_link_tag 'admin_edit_broker_form.css' %>
<body class = "admin-edit-broker">

  

  <div class = "admin-form-container mt-5">
    <%= form_with method: :put, scope: :broker, url: update_broker_admin_path , local: true do |f| %>
      <div class = "admin-form-edit">
        <h1>EDIT BROKER ACCOUNT</h1>
        <div class = "form-group">
          <%= f.label :first_name %><br />
          <%= f.text_field :first_name %>
        </div>

      <div class = "form-group">
        <%= f.label :last_name %><br />
        <%= f.text_field :last_name %>
      </div>

      <%= f.submit "Edit Account", class:'btn btn-light mb-3' %><br />
      <%= link_to "Go Back", admins_path, class:'btn btn-light mb-3' %>
      <% end %>
      </div>
  </div>
</body>

app/views/admins/edit_buyer.html.erb
<%= stylesheet_link_tag 'admin_edit_buyer_form.css' %>
<body class = "admin-edit-buyer">
<div class = "admin-form-container mt-5">
  <%= form_with method: :put, scope: :buyer, url: update_buyer_admin_path , local:true do |f| %>
    <div class = "admin-form-edit">
      <h1>EDIT BUYER ACCOUNT</h1>

      <div class = "form-group">
        <%= f.label :first_name %><br />
        <%= f.text_field :first_name %>
      </div>

      <div class = "form-group">
        <%= f.label :last_name %><br />
        <%= f.text_field :last_name %>
      </div>

      <%= f.submit "Edit Account", class:'btn btn-light mb-3' %><br />
      <%= link_to "Go Back", admins_path, class:'btn btn-light mb-3' %>
    </div>
  <% end %>
</div>
</body>

app/views/admins/index.html.erb
<%= stylesheet_link_tag 'admin_index.css' %>
<body class = "admin-index">

<h1 style="color:white;">Brokers</h1>
<div class= "table-responsive"> 
<%= link_to "New Broker", new_broker_admin_path, class: 'btn btn-success mb-3' %>
<%= link_to "Pending Brokers", pending_broker_signup_admin_path, class: 'btn btn-success mb-3' %>
  <table class="table table-striped">
    <thead class="thead-light">
      <tr>
        <th scope="col"></th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">View</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>
    <% @brokers.each do |broker| %>
      <tbody>
        <tr>
          <td scope="row"></td>
          <td><%= broker.first_name.capitalize %></td>
          <td><%= broker.last_name.capitalize %></td>
          <td><%= broker.email %></td>
          <td><%= link_to '👁‍🗨', broker_portfolio_path(broker) %></td>
          <td><%= link_to '📝', edit_broker_admin_path(broker) %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>
<br/><br/>

<h1 style="color:white;">Buyers</h1>
<div class= "table-responsive"> 
  <%= link_to "New Buyer", new_buyer_admin_path, class: 'btn btn-success mb-3' %>
  <br/><br/>
  <table class="table table-striped">
    <thead class="thead-light">
      <tr>
        <th scope="col"></th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">View</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>
    <% @buyers.each do |buyer| %>
      <tbody>
        <tr>
          <td scope="row"></td>
          <td><%= buyer.first_name.capitalize %></td>
          <td><%= buyer.last_name.capitalize %></td>
          <td><%= buyer.email %></td>
          <td><%= link_to '👁‍🗨', buyer_portfolio_path(buyer) %></td>
          <td><%= link_to '📝', edit_buyer_admin_path(buyer) %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>
<br/><br/>
</body>

app/views/admins/new_broker.html.erb
<%= stylesheet_link_tag 'admin_new_broker_form.css' %>
<body class = "admin-new-broker">
 

  <div class = "admin-form-container mt-5">
    <%= form_with method: :post, scope: :broker, url: create_broker_admin_path , local:true do |f| %>
      <div class = "admin-form-register">
        <h1>OPEN BROKER ACCOUNT</h1>
        <div class = "form-group">
          <%= f.label :first_name %><br />
          <%= f.text_field :first_name %>
        </div>

        <div class = "form-group">
          <%= f.label :last_name %><br />
          <%= f.text_field :last_name %>
        </div>

        <div class = "form-group">
          <%= f.label :email %><br />
          <%= f.text_field :email %>
        </div>

        <div class = "form-group">
          <%= f.label :password %><br />
          <%= f.password_field :password %>
        </div>

        <%= f.submit "Create Account", class:'btn btn-light mb-3' %><br />
        <%= link_to "Go Back", admins_path, class:'btn btn-light mb-3' %>
      </div>

     
    <% end %>
  </div>
</body>

app/views/admins/new_buyer.html.erb
<%= stylesheet_link_tag 'admin_new_buyer_form.css' %>
<body class = "admin-new-buyer">

<div class = "admin-form-container mt-5">
  <%= form_with method: :post, scope: :buyer, url: create_buyer_admin_path , local:true do |f| %>
    <div class = "admin-form-register">
      <h1>OPEN BUYER ACCOUNT</h1>
      <div class = "form-group">
        <%= f.label :first_name %><br />
        <%= f.text_field :first_name %>
      </div>

    <div class = "form-group">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>

    <div class = "form-group">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>

    <div class = "form-group">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>

    <%= f.submit "Create Account", class:'btn btn-light mb-3' %><br />
    <%= link_to "Go Back", admins_path, class:'btn btn-light mb-3' %>
    </div>
  <% end %>
</div>
</body>

app/views/admins/pending_broker_signup.erb
<%= stylesheet_link_tag 'admin_pending_broker_signup.css' %>
<body class = "admin-pending">
<<h1 style="color:white;">Brokers for Approval:</h1>
<div class= "table-responsive"> 
  <table class="table table-striped">
    <thead class="thead-light">
      <tr>
        <th scope="col"></th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th>Edit</th>
        <th>For Approval</th>
      </tr>
    </thead>
    <% @brokers.each do |broker| %>
      <tbody>
        <tr>
          <td scope="row"></td>
          <td><%= broker.first_name.capitalize %></td>
          <td><%= broker.last_name.capitalize %></td>
          <td><%= broker.email %></td>
          <td><%= link_to '📝', edit_broker_admin_path(broker) %></td>
          <td><%= link_to "Approve", approve_broker_admin_path(broker), class: 'btn btn-success', method: :put, data: { confirm: 'Are you sure you want to approve this broker?' } %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>
<br>
<%= link_to "Go Back", admins_path, class: 'btn btn-light' %>
</body>

app/views/admins/show_transaction.html.erb
<%= stylesheet_link_tag 'admin_transactions.css' %>
<body class = "admin-transactions">
<h1 style="color:white;">All Transactions</h1>
<div class= "table-responsive"> 
  <table class="table table-striped">
    <thead class="thead-light">
      <tr>
      <th scope="col"></th>
        <th scope="col">Stock ID</th>
        <th scope="col">Date and Time</th>
        <th scope="col">Ticker</th>
        <th scope="col">Company</th>
        <th scope="col">Price</th>
        <th scope="col">Broker</th>
        <th scope="col">Buyer</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total Amount</th>
      </tr>
    </thead>
    <% @buyer_stocks.each do |buyer_stock| %>
      <tbody>
        <tr>
          <td scope="row"></td>
          <td><%= buyer_stock.id %></td>
          <td><%= buyer_stock.created_at.strftime("%d-%^b-%Y, %l:%M %p UTC") %></td>
          <td class="text-success"><%= buyer_stock.broker_stock.stock.ticker %></td>
          <td><%= buyer_stock.broker_stock.stock.company %></td>
          <td class="text-success"><%= number_to_currency(buyer_stock.broker_stock.stock.price) %></td>
          <td class="font-italic text-warning"><%= buyer_stock.broker_stock.broker.first_name.capitalize %> <%= buyer_stock.broker_stock.broker.last_name.capitalize %></td>
          <td class="font-italic text-info"><%= buyer_stock.buyer.first_name.capitalize %> <%= buyer_stock.buyer.last_name.capitalize %></td>
          <td><%= buyer_stock.quantity %></td>
          <td class="text-success"><%= number_to_currency(buyer_stock.broker_stock.stock.price.to_f * buyer_stock.quantity) %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>
<br><br>
<%= link_to "Go Back", admins_path, class:'btn btn-light' %>
</body>