config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :admins, :controllers => { :registrations => :registrations }
  devise_for :brokers, :controllers => { :registrations => :registrations }
  devise_for :buyers, :controllers => { :registrations => :registrations }

  root to: "welcome#index"

  resources :admins
  resources :brokers
  resources :buyers
  resources :stocks
  resources :broker_stocks
  resources :buyer_stocks, only: [:create, :index]

  # for manually creating new broker and buyer accounts
  get 'admins/new/broker' => 'admins#new_broker', as: 'new_broker_admin'
  get 'admins/new/buyer' => 'admins#new_buyer', as: 'new_buyer_admin'
  post 'admins/create_broker' => 'admins#create_broker', as: 'create_broker_admin'
  post 'admins/create_buyer' => 'admins#create_buyer', as: 'create_buyer_admin'

  # for editing broker and buyer accounts
  get 'admins/:id/edit/broker' => 'admins#edit_broker', as: 'edit_broker_admin'
  get 'admins/:id/edit/buyer' => 'admins#edit_buyer', as: 'edit_buyer_admin'
  put 'admins/:id/update_broker' => 'admins#update_broker', as: 'update_broker_admin'
  put 'admins/:id/update_buyer' => 'admins#update_buyer', as: 'update_buyer_admin'


  get 'admins/pending/broker' => 'admins#pending_broker_signup', as: 'pending_broker_signup_admin'
  put 'admins/:id/approve_broker' => 'admins#approve_broker_signup', as: 'approve_broker_admin'

  get 'brokers/:id/portfolio' => 'brokers#show_portfolio', as: 'broker_portfolio'
  get 'buyers/:id/portfolio' => 'buyers#show_portfolio', as: 'buyer_portfolio'

  get 'brokers/:id/transaction' => 'brokers#show_transaction', as: 'broker_transaction'
  get 'buyers/:id/transaction' => 'buyers#show_transaction', as: 'buyer_transaction'
  get 'admins/show/transaction' => 'admins#show_transaction', as: 'all_transactions'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
class Stock < ApplicationRecord
  validates :ticker, presence: true
  validates :company, presence: true
  validates :price, presence: true

  has_many :broker_stocks
  has_many :brokers, through: :broker_stocks
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :test

  def index
   @stocks_search = Stock.all
  end

  def new
    @stock = Stock.new
  end

  def create
    @ticker = @client.company(params[:stock][:ticker]).symbol
    @company = @client.company(params[:stock][:ticker]).company_name
  
    @stock = Stock.find_or_create_by(ticker: @ticker, company: @company)

    @stock.price = @client.quote(params[:stock][:ticker]).latest_price
    
    if @stock.save
      redirect_to stock_path(@stock)
    else
      render :new
    end
  end

  def show
    @stock = Stock.find(params[:id])
  end

private
  def test
    @client = IEX::Api::Client.new(
    publishable_token: 'pk_b80fe862282642169f72829236149ccc',
    secret_token: Rails.application.credentials.secret_token,
    # secret_token: Rails.application.credentials.secret_token,
    endpoint: 'https://cloud.iexapis.com/v1'
    )
  end

  def stock_create_params
    params.require(:stock).permit(:ticker)
  end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/index.html.erb
<br/><br/>


STOCKS
<%= link_to "Find Stock", new_stock_path %>
<br/><br/>
<% if false %>
<p> MOST ACTIVE </p>
<table>
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Ticker</th>
      <th scope="col">Company</th>
      <th scope="col">Price</th>
      <th></th>
    </tr>
  </thead>
  <% @stocks.each do |stock| %>
    <tbody>
      <tr>
        <td scope="row"></td>
        <% quote = @client.quote(stock.symbol) %>
        <td><%= "#{stock.symbol}" %></td>
        <td><%= @client.company(stock.symbol).company_name %></td>
        <td><%= "#{quote.latest_price}" %></td>
        <td><%= link_to 'Buy', stocks_path %></td>
      </tr>
    </tbody>
  <% end %>
</table>
<% end %>
<p> SEARCHED </p>

<table>
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Ticker</th>
      <th scope="col">Company</th>
      <th scope="col">Price</th>
      <th></th>
    </tr>
  </thead>
  <% @stocks_search.each do |stock| %>
    <tbody>
      <tr>
        <td scope="row"></td>
        <td><%= stock.ticker %></td>
        <td><%= stock.company %></td>
        <td><%= stock.price %></td>
        <td><%= link_to 'Buy', broker_stocks_path(stock_id: stock.id), method: :post, data: { confirm: 'Are you sure you want to buy this?' } %></td>
      </tr>
    </tbody>
  <% end %>
</table>


<br/><br/>
<%= link_to "Welcome Page", root_path %>

app/views/stocks/new.html.erb
<%if broker_signed_in? %>
<div class="d-flex justify-content-center mb-2">
  <%= image_tag("broker.png", size: 100)%>
</div>
<h3 class="text-center text-light">BROKER</h3>
<br>
<div class="input-group rounded">
  <%= form_with method: :post, scope: :stock, url: stocks_path, class: "d-flex m-auto", local:true do |f| %>
    <%= f.text_field :ticker, class: "form-control-lg rounded mr-1", "placeholder": "Search Ticker", "aria-label": "Search", "aria-describedby": "search-addon" %>
    <%= f.submit "🔍", class: "input-group-text", "id": "search-addon" %>
  <% end %>
</div>
<%end%>
<%if buyer_signed_in? %>
<div class="d-flex justify-content-center mb-2">
  <%= image_tag("buyer.png", size: 100)%>
</div>
<h3 class="text-center text-light">BUYER</h3>
<br>
<div class="d-flex justify-content-center">
  <%= link_to "Buy Stocks", broker_stocks_path, class: "btn btn-success btn-lg" %>
</div>
<%end%>

app/views/stocks/show.html.erb
<%= stylesheet_link_tag 'broker_show.css' %>
<body class="broker-bg">
 <div class="container">
		<div class="row stock-bg d-flex justify-content-center text-center">
            <div class="well">
        		<h2 class="text-light"><small class="h6">Ticker:</small> <br><b><%= @stock.ticker %></b></h2>
                <h2 class="text-light"><small class="h6">Company:</small> <br><b><%= @stock.company %></b></h2>
        		<h3 class="text-light h1"><small class="h6">Stock Price:</small><br> <b><%= number_to_currency(@stock.price) %></b></h3>
                <br>
                <% if current_broker.stocks.include?(@stock) %>
                    <p class='text-danger font-weight-bold'>You already added this stock to your list</p>
                    <%= link_to 'Back', :back, class: 'btn btn-info' %>
                <% else %>
                    <%= link_to 'Add to my portfolio', broker_stocks_path(stock_id: @stock.id), method: :post, data: { confirm: 'Are you sure you want to buy this?' }, class: "btn btn-info" %>
                <% end %>
        	</div>
        </div>
</body>