config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :admins, :controllers => { :registrations => :registrations }
  devise_for :brokers, :controllers => { :registrations => :registrations }
  devise_for :buyers, :controllers => { :registrations => :registrations }

  root to: "welcome#index"

  resources :admins
  resources :brokers
  resources :buyers
  resources :stocks
  resources :broker_stocks
  resources :buyer_stocks, only: [:create, :index]

  # for manually creating new broker and buyer accounts
  get 'admins/new/broker' => 'admins#new_broker', as: 'new_broker_admin'
  get 'admins/new/buyer' => 'admins#new_buyer', as: 'new_buyer_admin'
  post 'admins/create_broker' => 'admins#create_broker', as: 'create_broker_admin'
  post 'admins/create_buyer' => 'admins#create_buyer', as: 'create_buyer_admin'

  # for editing broker and buyer accounts
  get 'admins/:id/edit/broker' => 'admins#edit_broker', as: 'edit_broker_admin'
  get 'admins/:id/edit/buyer' => 'admins#edit_buyer', as: 'edit_buyer_admin'
  put 'admins/:id/update_broker' => 'admins#update_broker', as: 'update_broker_admin'
  put 'admins/:id/update_buyer' => 'admins#update_buyer', as: 'update_buyer_admin'


  get 'admins/pending/broker' => 'admins#pending_broker_signup', as: 'pending_broker_signup_admin'
  put 'admins/:id/approve_broker' => 'admins#approve_broker_signup', as: 'approve_broker_admin'

  get 'brokers/:id/portfolio' => 'brokers#show_portfolio', as: 'broker_portfolio'
  get 'buyers/:id/portfolio' => 'buyers#show_portfolio', as: 'buyer_portfolio'

  get 'brokers/:id/transaction' => 'brokers#show_transaction', as: 'broker_transaction'
  get 'buyers/:id/transaction' => 'buyers#show_transaction', as: 'buyer_transaction'
  get 'admins/show/transaction' => 'admins#show_transaction', as: 'all_transactions'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav id="navbar1" class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">

	
    <span class="navbar-brand">MTS</span>

    <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1" aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation"><span class="dark-blue-text">
    <i class="fa fa-bars fa-1x"></i></span>
    </button>
    
   <div class="collapse navbar-collapse" id="navbarSupportedContent1">
     <ul class="nav navbar-nav ml-auto">
	 
      <% if admin_signed_in? %>
        <li class="nav-item"> <%= link_to "Home", admins_path, class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to "Show All Transactions", all_transactions_path, class: "nav-link" %></li>
        <li class="nav-item active"> <%= link_to 'Logout',  destroy_admin_session_path, method: :delete, class: "btn btn-danger" %></li>
      
      <%elsif broker_signed_in? %>
        <% stylesheet_link_tag "dropdown.css" %>
        <li class="nav-item active mx-4">
          <%= link_to broker_portfolio_path(current_broker), class: "nav-link" do %>
            Portfolio<span class="sr-only">(current)</span>
          <% end %>
        </li>
        <li class="nav-item active mx-4">
          <%= link_to broker_transaction_path(current_broker), class: "nav-link" do %>
            Transactions<span class="sr-only">(current)</span>
          <% end %>
        </li>
        <li class="nav-item active mx-4">
          <div class="dropdown">
            <a class="nav-link active" href="#">Account</a>
            <div class="dropdown-content p-4 drop">
                <p>name:<br><strong class="text-capitalize"><%= current_broker.first_name %> <%= current_broker.last_name %></strong></p>
                <p>email: <strong><%= current_broker.email %></strong></p>
                <p><%= link_to "Edit", edit_broker_registration_path, class: "btn btn-success" %></p>
            </div>
          </div>
        </li>
        <li class="nav-item active mx-4">
          <%= link_to 'Logout',  destroy_broker_session_path, method: :delete, class: "btn btn-danger" %>
        </li>

      <%elsif buyer_signed_in? %>
        <% stylesheet_link_tag "dropdown.css" %>
        <li class="nav-item active mx-4">
          <%= link_to buyer_portfolio_path(current_buyer), class: "nav-link" do %>
            Portfolio<span class="sr-only">(current)</span>
          <% end %>
        </li>
        <li class="nav-item active mx-4">
          <%= link_to buyer_transaction_path(current_buyer), class: "nav-link" do %>
            Transactions<span class="sr-only">(current)</span>
          <% end %>
        </li>
        <li class="nav-item active mx-4">
          <div class="dropdown">
            <a class="nav-link active" href="#">Account</a>
            <div class="dropdown-content p-4 drop">
                <p>name:<br><strong class="text-capitalize"><%= current_buyer.first_name %> <%= current_buyer.last_name %></strong></p>
                <p>email: <strong><%= current_buyer.email %></strong></p>
                <p><%= link_to "Edit", edit_buyer_registration_path, class: "btn btn-success" %></p>
            </div>
          </div>
        </li>
        <li class="nav-item active mx-4">
          <%= link_to 'Logout',  destroy_buyer_session_path, method: :delete, class: "btn btn-danger" %>
        </li>
      <%else%>
        <li class="nav-item"> <%= link_to "Home Page", root_path, class: "nav-link" %></li>
        <li class="nav-item ">  <%= link_to 'Login', new_buyer_session_path, class: "btn btn-success"%> </li>
    <% end %>
    </ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Questrial&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital@1&display=swap" rel="stylesheet">
  </head>

  <body>
  <%= render 'layouts/header'%>
  <div class = "container">
  <% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">X</button>
  </div>
  <% end %>
  <% if alert %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">X</button>
  </div>
  <% end %>
  
  

    <%= yield %>
   
  </div>
  </body>
</html>